language: go
os:
  - linux
  - osx
go:
  - 1.11.x
env:
  - GOOS=windows GOARCH=amd64
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=386
  - GOOS=linux GOARCH=arm
matrix:
  fast_finish: true

before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -v -service=travis-ci
